# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "golang.org/x/sys"
  revision = "320cb01ddbbf0473674c2585f9b6e245721de355"

[[override]]
  name = "github.com/miekg/dns"
  revision = "48ab6605c66ac797e07f615101c3e9e10e932b66"

[[override]]
  name = "github.com/armon/go-metrics"
  revision = "fbf75676ee9c0a3a23eb0a4d9220a3612cfbd1ed"

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"

[[constraint]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"

[[constraint]]
  name = "github.com/hashicorp/memberlist"
  revision = "7c7d6bae440fb7c6dcde850672e0f68263f9e29c"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "6d9ae300aaf85d6acd2e5424081c7fcddb21dab8"

[prune]
  go-tests = true
  unused-packages = true
